package corba;


/**
* corba/_IShoppingCartImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cart.idl
* Saturday, 9 June 2018 13:24:38 o'clock BST
*/

public abstract class _IShoppingCartImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements corba.IShoppingCart, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _IShoppingCartImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addToCart", new java.lang.Integer (0));
    _methods.put ("getItems", new java.lang.Integer (1));
    _methods.put ("order", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/IShoppingCart/addToCart
       {
         corba.OrderItem items = corba.OrderItemHelper.read (in);
         this.addToCart (items);
         out = $rh.createReply();
         break;
       }

       case 1:  // corba/IShoppingCart/getItems
       {
         corba.OrderItem $result[] = null;
         $result = this.getItems ();
         out = $rh.createReply();
         corba.OrderItemListHelper.write (out, $result);
         break;
       }

       case 2:  // corba/IShoppingCart/order
       {
         this.order ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/IShoppingCart:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _IShoppingCartImplBase
