package corba;

/**
* corba/CategoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cart.idl
* Saturday, 9 June 2018 13:24:38 o'clock BST
*/

public final class CategoryHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.Category value = null;

  public CategoryHolder ()
  {
  }

  public CategoryHolder (corba.Category initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.CategoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.CategoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.CategoryHelper.type ();
  }

}
