package corba;


/**
* corba/Category.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cart.idl
* Saturday, 9 June 2018 13:24:38 o'clock BST
*/

public final class Category implements org.omg.CORBA.portable.IDLEntity
{
  public String c_name = null;

  public Category ()
  {
  } // ctor

  public Category (String _c_name)
  {
    c_name = _c_name;
  } // ctor

} // class Category
