package corba;


/**
* corba/IShoppingCartOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cart.idl
* Saturday, 9 June 2018 13:24:38 o'clock BST
*/

public interface IShoppingCartOperations 
{
  void addToCart (corba.OrderItem items);
  corba.OrderItem[] getItems ();
  void order ();
} // interface IShoppingCartOperations
