package corba;


/**
* corba/IStockDisplayHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cart.idl
* Saturday, 9 June 2018 13:24:38 o'clock BST
*/

abstract public class IStockDisplayHelper
{
  private static String  _id = "IDL:corba/IStockDisplay:1.0";

  public static void insert (org.omg.CORBA.Any a, corba.IStockDisplay that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corba.IStockDisplay extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (corba.IStockDisplayHelper.id (), "IStockDisplay");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corba.IStockDisplay read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IStockDisplayStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corba.IStockDisplay value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static corba.IStockDisplay narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba.IStockDisplay)
      return (corba.IStockDisplay)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba._IStockDisplayStub stub = new corba._IStockDisplayStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static corba.IStockDisplay unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba.IStockDisplay)
      return (corba.IStockDisplay)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba._IStockDisplayStub stub = new corba._IStockDisplayStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
