package corba;


/**
* corba/IStockDisplayOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cart.idl
* Saturday, 9 June 2018 13:24:38 o'clock BST
*/

public interface IStockDisplayOperations 
{
  corba.Product[] giveItems ();
} // interface IStockDisplayOperations
