package corba;


/**
* corba/OrderItem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cart.idl
* Saturday, 9 June 2018 13:24:38 o'clock BST
*/

public final class OrderItem implements org.omg.CORBA.portable.IDLEntity
{
  public corba.Product product = null;
  public int quantity = (int)0;

  public OrderItem ()
  {
  } // ctor

  public OrderItem (corba.Product _product, int _quantity)
  {
    product = _product;
    quantity = _quantity;
  } // ctor

@Override
public String toString() {
	return "Ordered " + product + "  in /" + quantity + "/ units.";
}

  
  
} // class OrderItem
