package corba;


/**
* corba/Product.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cart.idl
* Saturday, 9 June 2018 13:24:38 o'clock BST
*/

public final class Product implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  
  public corba.Category category = null;

  public Product ()
  {
  } // ctor

  public Product (String _name, corba.Category _category)
  {
    name = _name;
   
    category = _category;
  } // ctor

@Override
public String toString() {
	return " /" + name + "/  of /" + category.c_name + "/";
}

  
} // class Product
