package corba;


/**
* corba/ProductsListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cart.idl
* Saturday, 9 June 2018 13:24:38 o'clock BST
*/

public final class ProductsListHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.Product value[] = null;

  public ProductsListHolder ()
  {
  }

  public ProductsListHolder (corba.Product[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.ProductsListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.ProductsListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.ProductsListHelper.type ();
  }

}
