package corba;

/**
* corba/ShoppingCartExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cart.idl
* Saturday, 9 June 2018 13:24:38 o'clock BST
*/

public final class ShoppingCartExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.ShoppingCartException value = null;

  public ShoppingCartExceptionHolder ()
  {
  }

  public ShoppingCartExceptionHolder (corba.ShoppingCartException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.ShoppingCartExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.ShoppingCartExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.ShoppingCartExceptionHelper.type ();
  }

}
